<!DOCTYPE html>
<html lang="es"><head>
<script src="slides-outline_files/libs/clipboard/clipboard.min.js"></script>
<script src="slides-outline_files/libs/quarto-html/tabby.min.js"></script>
<script src="slides-outline_files/libs/quarto-html/popper.min.js"></script>
<script src="slides-outline_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="slides-outline_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="slides-outline_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="slides-outline_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Sebastian Carmona Estrada">
  <title>Design and Development of a Multispectral Imagery System for Land Cover and Land Use Monitoring in Colombia</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="slides-outline_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="slides-outline_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="slides-outline_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link href="slides-outline_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="slides-outline_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="slides-outline_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="slides-outline_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Design and Development of a Multispectral Imagery System for Land Cover and Land Use Monitoring in Colombia</h1>
  <p class="subtitle">Master in Applied Physics · Universidad EAFIT</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Sebastian Carmona Estrada 
</div>
        <p class="quarto-title-affiliation">
            School of Applied Sciences and Engineering · HuMath Space Systems
          </p>
    </div>
</div>

</section>
<section id="portada" class="title-slide slide level1 center">
<h1>Portada</h1>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>Autor:</strong> Sebastian Carmona Estrada</li>
<li><strong>Directora:</strong> Prof.&nbsp;Dr.&nbsp;Eng. Olga Lucia Quintero Montoya</li>
<li><strong>Programa:</strong> Master in Sciences / Master in Applied Physics</li>
<li><strong>Facultad:</strong> School of Applied Sciences and Engineering</li>
<li><strong>Universidad:</strong> Universidad EAFIT</li>
<li><strong>Grupo:</strong> HuMath Space Systems</li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="slides_format/logos/logo-humath-space_1.png" width="180"></p>
</div></div>
</section>

<section>
<section id="planteamiento-del-problema" class="title-slide slide level1 center">
<h1>1. Planteamiento del problema</h1>

</section>
<section id="problema-central" class="slide level2">
<h2>Problema central</h2>
<ul>
<li>En 2024 Colombia registró <strong>113.608 ha deforestadas</strong>, con concentración crítica en el arco amazónico (IDEAM, 31-jul-2025).</li>
<li>Entre enero-septiembre de 2025 en la Amazonía se estimaron <strong>36.280 ha</strong>, y <strong>98 %</strong> del fenómeno se concentró en Meta, Caquetá, Guaviare y Putumayo (MinAmbiente, 30-dic-2025).</li>
<li>El mapa oficial nacional de coberturas (periodo 2020) está en <strong>escala 1:100.000</strong>; esta escala es útil para análisis nacionales, pero limitada para decisiones finas operativas/prediales.</li>
</ul>
<!--
Justificación para exposición (no visible en la diapositiva):
1) La magnitud y concentración territorial de la deforestación exige monitoreo más frecuente (subanual) para reacción temprana.
2) La escala 1:100.000 es adecuada para planeación macro, pero insuficiente para seguimiento detallado de frentes de cambio locales.
3) Por eso se justifica una solución de monitoreo más densa en tiempo y mayor detalle espacial desde plataformas aéreas.

Fuentes usadas:
- IDEAM (31-jul-2025): https://www.ideam.gov.co/sala-de-prensa/noticia/en-2024-colombia-consolido-la-segunda-cifra-de-deforestacion-mas-baja-en-de-la-historia
- MinAmbiente (30-dic-2025): https://www.minambiente.gov.co/amazonia-colombiana-reduce-en-25-la-deforestacion-estimada-entre-enero-y-septiembre-de-2025/
- IDEAM Coberturas 100K periodo 2020 (item info): https://visualizador.ideam.gov.co/gisserver/rest/services/Capascache/Cobertura_de_la_Tierra_100K_Periodo_2020_l%C3%ADmite_administrativo/MapServer/info/iteminfo
-->
</section>
<section id="brecha-tecnológica-en-colombia" class="slide level2">
<h2>Brecha tecnológica en Colombia</h2>
<ul>
<li>La nubosidad persistente reduce a menos de 5 escenas satelitales libres de nubes por mes en muchas zonas.</li>
<li>La resolución de misiones gratuitas no captura variabilidad intraparcela: Landsat-8 (30 m) y Sentinel-2 (10 m).</li>
<li>Las cámaras multiespectrales comerciales siguen siendo costosas (normalmente &gt; 7000 USD).</li>
<li>A nivel local no hay una solución VIS/NIR diseñada y fabricada en Colombia con costo objetivo &lt; 1500 USD y calibración rigurosa.</li>
</ul>
</section>
<section id="pregunta-de-investigación" class="slide level2">
<h2>Pregunta de investigación</h2>
<ul>
<li>¿Cómo desarrollar y caracterizar un sistema óptico multiespectral VIS-NIR, de bajo costo y baja masa, para plataformas aéreas que opere bajo condiciones atmosféricas tropicales en Colombia?</li>
</ul>
</section>
<section id="hipótesis-de-trabajo" class="slide level2">
<h2>Hipótesis de trabajo</h2>
<ul>
<li>Integrar una óptica VIS de 8.5 mm f/1.8 y una NIR de 8 mm f/2.5 con sensores AR0521 (VIS) y AR0522 (NIR).</li>
<li>Aplicar calibración geométrica basada en ISO 12233 y calibración radiométrica mediante combinaciones de filtros caracterizadas en laboratorio.</li>
<li>Con ello se espera lograr GSD &lt;= 2 m a 5 km, error radiométrico intercanal &lt; 5 %, costo de materiales &lt;= 1500 USD y masa total &lt; 2 kg.</li>
</ul>
</section>
<section id="objetivo-general-y-objetivos-específicos" class="slide level2">
<h2>Objetivo general y objetivos específicos</h2>
<ul>
<li>Objetivo general: diseñar, construir, calibrar y caracterizar un sistema óptico multiespectral VIS/NIR para integración en plataforma aérea.</li>
<li>Definir la arquitectura óptica y mecánica bajo restricciones de masa, volumen, resolución y costo.</li>
<li>Procurar e integrar sensores, lentes, filtros y electrónica de adquisición/almacenamiento.</li>
<li>Validar desempeño en pruebas de laboratorio y de vuelo.</li>
<li>Determinar respuesta geométrica y espectral para soportar productos georreferenciados de monitoreo ambiental.</li>
</ul>
</section>
<section id="alcance-y-limitaciones" class="slide level2">
<h2>Alcance y limitaciones</h2>
<ul>
<li>Rango espectral objetivo del sistema: 400-900 nm.</li>
<li>Restricciones de integración: volumen aproximado 100 x 100 x 150 mm y masa total &lt; 2 kg.</li>
<li>Ventana operativa evaluada: 50-5000 m de altitud sobre el terreno.</li>
<li>El trabajo se centra en diseño, integración y calibración del sistema; no incluye desarrollo de modelos de clasificación o estimación de variables biofísicas.</li>
</ul>
</section></section>
<section>
<section id="diseño-del-dispositivo-capítulo-2" class="title-slide slide level1 center">
<h1>2. Diseño del dispositivo (Capítulo 2)</h1>

</section>
<section id="propósito-del-diseño" class="slide level2">
<h2>Propósito del diseño</h2>
<ul>
<li>Se partió de una matriz de <strong>8 sistemas ópticos</strong> para seleccionar la configuración VIS/NIR con mejor desempeño para la misión C3.</li>
<li>El proceso combinó simulación óptica, análisis de restricciones de integración y evaluación costo-rendimiento.</li>
<li>El criterio final fue técnico-operativo: resolución suficiente, cobertura útil, bajo consumo y factibilidad de fabricación local.</li>
</ul>
</section>
<section id="requerimientos-ópticos-y-criterios-de-diseño" class="slide level2">
<h2>Requerimientos ópticos y criterios de diseño</h2>
<ul>
<li>Resolución espacial objetivo: <strong>MTF &gt;= 40 lp/mm</strong> al 30 % de contraste.</li>
<li>Cobertura: campo de visión útil para misiones entre <strong>50 m y 5000 m AGL</strong>.</li>
<li>Restricciones de integración C3: masa, volumen, autonomía y costo.</li>
<li>Condición de operación: iluminación ambiental diurna.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parámetro</th>
<th>Requisito de diseño</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Masa del payload</td>
<td>&lt;= 2 kg</td>
</tr>
<tr class="even">
<td>Dimensiones máximas</td>
<td>100 x 100 x 150 mm</td>
</tr>
<tr class="odd">
<td>Tiempo de misión</td>
<td>&lt;= 3 h</td>
</tr>
<tr class="even">
<td>MTF (30 % contraste)</td>
<td>&gt;= 40 lp/mm</td>
</tr>
<tr class="odd">
<td>Resolución @ 50 m</td>
<td>&lt;= 7.35 cm</td>
</tr>
<tr class="even">
<td>Resolución @ 1000 m</td>
<td>&lt;= 1.47 m</td>
</tr>
<tr class="odd">
<td>Resolución @ 5000 m</td>
<td>&lt;= 7.35 m</td>
</tr>
<tr class="even">
<td>Presupuesto objetivo</td>
<td>&lt;= 1500 USD</td>
</tr>
</tbody>
</table>
</section>
<section id="terminología-usada-en-el-diseño-óptico" class="slide level2">
<h2>Terminología usada en el diseño óptico</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Término</th>
<th>Significado práctico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MTF</td>
<td>Capacidad de preservar contraste en detalle fino; se usa 30 % como punto de comparación.</td>
</tr>
<tr class="even">
<td>AFOV</td>
<td>Campo angular de visión; mayor AFOV implica más cobertura por imagen.</td>
</tr>
<tr class="odd">
<td>FOV</td>
<td>Cobertura lineal en tierra para una altura dada.</td>
</tr>
<tr class="even">
<td>Distancia focal</td>
<td>Controla aumento y cobertura; focal larga mejora detalle y reduce cobertura.</td>
</tr>
<tr class="odd">
<td>Apertura (f/#)</td>
<td>Controla entrada de luz y desempeño en frecuencias espaciales altas.</td>
</tr>
</tbody>
</table>
</section>
<section id="plataforma-de-adquisición-y-procesamiento" class="slide level2">
<h2>Plataforma de adquisición y procesamiento</h2>
<ul>
<li>Núcleo de procesamiento: <strong>Raspberry Pi 4B (8 GB)</strong> por costo, modularidad y ecosistema de software.</li>
<li>Cámaras Alvium conectadas por USB 3 con stack en Python para adquisición y control.</li>
<li>Se descartó GPU dedicada (Jetson) en esta versión por consumo, costo y complejidad.</li>
<li>Arquitectura preparada para migrar a inferencia en borde en iteraciones futuras.</li>
</ul>
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li>Filosofía de diseño: plug-and-play, mantenible y replicable.</li>
<li>Integración directa VIS/NIR + georreferenciación.</li>
</ul>
</div><div class="column" style="width:45%;">
<p><img data-src="Figures/C2/esquea_sis_imagen.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="matriz-de-objetivos-candidatos-8-sistemas" class="slide level2">
<h2>Matriz de objetivos candidatos (8 sistemas)</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Sistema</th>
<th>Objetivo</th>
<th>Focal [mm]</th>
<th>AFOV [deg]</th>
<th>Apertura</th>
<th>MTF@30% [lp/mm]</th>
<th>Peso [g]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>16 mm HPr (EO)</td>
<td>16</td>
<td>42.2</td>
<td>f/16</td>
<td>62</td>
<td>138</td>
</tr>
<tr class="even">
<td>2</td>
<td>50 mm HPr (EO)</td>
<td>50</td>
<td>10.1</td>
<td>f/2.8</td>
<td>180</td>
<td>–</td>
</tr>
<tr class="odd">
<td>3</td>
<td>25 mm HPr (EO)</td>
<td>25</td>
<td>27.8</td>
<td>f/1.8</td>
<td>40</td>
<td>78</td>
</tr>
<tr class="even">
<td>4</td>
<td>16 mm HPr (EO)</td>
<td>16</td>
<td>42.2</td>
<td>f/1.8</td>
<td>128</td>
<td>138</td>
</tr>
<tr class="odd">
<td>5</td>
<td>4 mm Basler</td>
<td>4</td>
<td>109.0</td>
<td>f/1.8</td>
<td>–</td>
<td>–</td>
</tr>
<tr class="even">
<td>6</td>
<td>8 mm HEO NIR (EO)</td>
<td>8</td>
<td>29.9</td>
<td>f/2.5</td>
<td>120</td>
<td>4</td>
</tr>
<tr class="odd">
<td>7</td>
<td>8.5 mm Cr (EO)</td>
<td>8.5</td>
<td>28.2</td>
<td>f/1.8</td>
<td>85</td>
<td>60</td>
</tr>
<tr class="even">
<td>8</td>
<td>12.5 mm Rugged Blue (EO)</td>
<td>12.5</td>
<td>19.4</td>
<td>f/2.5</td>
<td>150</td>
<td>5</td>
</tr>
</tbody>
</table>
</section>
<section id="lectura-técnica-de-la-matriz-de-objetivos" class="slide level2">
<h2>Lectura técnica de la matriz de objetivos</h2>
<ul>
<li><strong>Sistema 2</strong>: máxima nitidez teórica (MTF alta), pero AFOV muy estrecho.</li>
<li><strong>Sistema 5</strong>: cobertura extrema, pero sin curva MTF reportada por fabricante.</li>
<li><strong>Sistemas 6 y 7</strong>: compromiso robusto entre AFOV, MTF, masa y costo.</li>
<li>En régimen aéreo (hiperfoco), la profundidad de campo deja de ser limitante; domina el balance apertura-peso-costo.</li>
</ul>
</section>
<section id="preselección-de-sensores-de-imagen" class="slide level2">
<h2>Preselección de sensores de imagen</h2>
<ul>
<li>Parámetros evaluados: resolución, tamaño de píxel, tipo de obturación, bits, masa y consumo.</li>
<li>AR0521/AR0522 fueron priorizados por <strong>consumo bajo (~2.2 W)</strong> y costo.</li>
<li>Se asumió rolling shutter como compromiso frente a global shutter por restricciones del proyecto.</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Sistema</th>
<th>Sensor</th>
<th>H x V [px]</th>
<th>Pixel [um]</th>
<th>Shutter</th>
<th>Bits</th>
<th>Peso [g]</th>
<th>Potencia [W]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1,3,4</td>
<td>Alvium U-2040 (IMX541)</td>
<td>4512 x 4512</td>
<td>2.74</td>
<td>Global</td>
<td>12</td>
<td>65</td>
<td>3.9</td>
</tr>
<tr class="even">
<td>2</td>
<td>Alvium U-2050 (IMX183)</td>
<td>5496 x 3672</td>
<td>2.40</td>
<td>Rolling</td>
<td>10</td>
<td>65</td>
<td>3.2</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Basler acA1920 (IMX249)</td>
<td>1920 x 1200</td>
<td>5.86</td>
<td>Global</td>
<td>12</td>
<td>90</td>
<td>3.9</td>
</tr>
<tr class="even">
<td>6</td>
<td>Alvium U-501m (AR0522)</td>
<td>2592 x 1944</td>
<td>2.20</td>
<td>Rolling</td>
<td>10</td>
<td>65</td>
<td>2.2</td>
</tr>
<tr class="odd">
<td>7,8</td>
<td>Alvium U-500c (AR0521)</td>
<td>2592 x 1944</td>
<td>2.20</td>
<td>Rolling</td>
<td>10</td>
<td>60</td>
<td>2.2</td>
</tr>
</tbody>
</table>

<img data-src="Figures/C2/espectro.png" style="width:70.0%" class="r-stretch"></section>
<section id="modelo-teórico-fov-y-resolución-en-tierra" class="slide level2">
<h2>Modelo teórico: FOV y resolución en tierra</h2>
<p><span class="math display">\[
AFOV = 2\tan^{-1}\left(\frac{H_{sensor}}{2f}\right)
\]</span></p>
<p><span class="math display">\[
FOV = 2 \cdot WD \cdot \tan\left(\frac{AFOV}{2}\right), \quad PMAG=\frac{H_{sensor}}{FOV}
\]</span></p>
<p><span class="math display">\[
f_{obj}=f_{im}\cdot PMAG,\quad f_{sensor}=\frac{1}{2s}
\]</span></p>
<p><span class="math display">\[
\Delta_{ground}=\frac{1}{2f_{obj}}\cdot\frac{1}{1000},\quad
\Delta_{pix}=\frac{1}{2f_{sensor}}\cdot\frac{1}{1000}
\]</span></p>
<ul>
<li>Se evaluaron altitudes de <strong>50 m, 1000 m y 5000 m</strong> para los 8 sistemas.</li>
</ul>
</section>
<section id="resultados-teóricos-por-altitud-sistemas-finalistas" class="slide level2">
<h2>Resultados teóricos por altitud (sistemas finalistas)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Altitud</th>
<th>FOV Sys.6 (NIR)</th>
<th><span class="math inline">\(\Delta_{MTF}\)</span> Sys.6</th>
<th>FOV Sys.7 (VIS)</th>
<th><span class="math inline">\(\Delta_{MTF}\)</span> Sys.7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>50 m</td>
<td>26.73 m</td>
<td>1.9 cm</td>
<td>25.16 m</td>
<td>3.4 cm</td>
</tr>
<tr class="even">
<td>1000 m</td>
<td>534.6 m</td>
<td>39.1 cm</td>
<td>503.2 m</td>
<td>69.2 cm</td>
</tr>
<tr class="odd">
<td>5000 m</td>
<td>2673 m</td>
<td>1.95 m</td>
<td>2516 m</td>
<td>3.46 m</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sistema</th>
<th>FOV @ 5000 m</th>
<th><span class="math inline">\(\Delta_{MTF}\)</span> @ 5000 m</th>
<th>Lectura de diseño</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>881 m</td>
<td>0.186 m</td>
<td>Muy alta resolución, baja cobertura</td>
</tr>
<tr class="even">
<td>4</td>
<td>3863 m</td>
<td>1.221 m</td>
<td>Buen compromiso técnico, costo alto</td>
</tr>
<tr class="odd">
<td>6</td>
<td>2673 m</td>
<td>1.953 m</td>
<td>Balance costo-masa-resolución</td>
</tr>
<tr class="even">
<td>7</td>
<td>2516 m</td>
<td>3.460 m</td>
<td>Complemento VIS para fusión multicanal</td>
</tr>
</tbody>
</table>
</section>
<section id="tendencias-obtenidas-en-la-simulación" class="slide level2">
<h2>Tendencias obtenidas en la simulación</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C2/disenofov.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C2/design_res.png" style="width:100.0%"></p>
</div></div>
<ul>
<li>En todos los casos: <span class="math inline">\(\Delta_{MTF} &gt; \Delta_{pix}\)</span>, por limitación óptica sobre el límite de muestreo del sensor.</li>
<li>Focal larga: más nitidez y menos cobertura.</li>
<li>Focal corta: más cobertura y menos nitidez.</li>
<li>La pareja 6-7 mantiene geometría similar, favoreciendo el registro VIS/NIR.</li>
</ul>
</section>
<section id="selección-final-y-justificación-de-diseño" class="slide level2">
<h2>Selección final y justificación de diseño</h2>
<ul>
<li>Selección final: <strong>Sistema 6 (NIR) + Sistema 7 (VIS)</strong>.</li>
<li>Cumple simultáneamente cobertura, costo, masa y consumo para misión C3.</li>
<li>Permite integración multiespectral con desalineamiento reducido entre canales.</li>
<li>Define la línea base para procura, construcción e integración del capítulo siguiente.</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Canal</th>
<th>Sistema final</th>
<th>Lente</th>
<th>Sensor</th>
<th>Costo aproximado (sensor+lente)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NIR</td>
<td>6</td>
<td>8 mm f/2.5</td>
<td>AR0522</td>
<td>541 USD</td>
</tr>
<tr class="even">
<td>VIS</td>
<td>7</td>
<td>8.5 mm f/1.8</td>
<td>AR0521</td>
<td>777 USD</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indicador global</th>
<th>Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Masa de payload (meta &lt;= 2 kg)</td>
<td>Factible</td>
</tr>
<tr class="even">
<td>Presupuesto óptico (meta &lt;= 1500 USD)</td>
<td>Cumplido</td>
</tr>
<tr class="odd">
<td>Ventana operativa 50-5000 m</td>
<td>Cumplida</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="procura-y-construcción-del-dispositivo-capítulo-3" class="title-slide slide level1 center">
<h1>3. Procura y construcción del dispositivo (Capítulo 3)</h1>

</section>
<section id="procura-de-componentes-y-estrategia-de-integración" class="slide level2">
<h2>Procura de componentes y estrategia de integración</h2>
<ul>
<li>La procura priorizó componentes disponibles comercialmente, costo controlado y compatibilidad mecánica.</li>
<li>Se articuló una estrategia colaborativa EAFIT-KTH para integrar plataforma aérea y payload.</li>
<li>La financiación de componentes ópticos/electrónicos se apalancó desde el proyecto 4DAir.</li>
<li>La fabricación e integración se ejecutó con enfoque iterativo para reducir riesgo técnico.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sub-sistema</th>
<th>Decisión técnica</th>
<th>Razón principal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cámara VIS</td>
<td>Alvium U-500c + 8.5 mm</td>
<td>Balance resolución/costo</td>
</tr>
<tr class="even">
<td>Cámara NIR</td>
<td>Alvium U-501m + 8 mm</td>
<td>Cobertura NIR y bajo peso</td>
</tr>
<tr class="odd">
<td>Cómputo</td>
<td>Raspberry Pi 4</td>
<td>Integración simple y robusta</td>
</tr>
<tr class="even">
<td>Carcasa</td>
<td>PET-G impreso 3D</td>
<td>Resistencia y manufactura local</td>
</tr>
</tbody>
</table>
</section>
<section id="construcción-de-sistemas-ópticos-vis-y-nir" class="slide level2">
<h2>Construcción de sistemas ópticos VIS y NIR</h2>
<ul>
<li>Sistema NIR: U-501m + lente 8 mm f/2.5 + filtro pasabanda 850 nm.</li>
<li>Sistema VIS: U-500c + lente 8.5 mm + filtro UV/IR cut para aislar visible.</li>
<li>Diseño modular para facilitar mantenimiento, reemplazo y ajuste.</li>
<li>Conexión USB directa a la unidad de adquisición para simplificar cableado.</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Canal</th>
<th>Sensor</th>
<th>Lente</th>
<th>Filtro</th>
<th>Resolución nativa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VIS</td>
<td>Alvium U-500c (AR0521)</td>
<td>8.5 mm f/1.3</td>
<td>UV/IR-cut (370-750 nm)</td>
<td>2592 x 1944</td>
</tr>
<tr class="even">
<td>NIR</td>
<td>Alvium U-501m (AR0522)</td>
<td>8 mm f/2.5</td>
<td>BP 850 nm (FWHM 50 nm)</td>
<td>2592 x 1944</td>
</tr>
</tbody>
</table>
</section>
<section id="cad-y-ensamblaje-mecánico-del-prototipo" class="slide level2">
<h2>CAD y ensamblaje mecánico del prototipo</h2>
<ul>
<li>El encapsulado se desarrolló en PET-G por su rigidez, resistencia y estabilidad térmica.</li>
<li>Integración mecánica dentro de la bahía del C3 sin rediseño estructural de aeronave.</li>
<li>Masa final del dispositivo: 1810 g (dentro del requisito &lt;= 2 kg).</li>
<li>Arquitectura interna: módulo VIS, módulo NIR, cómputo, energía y sensado auxiliar.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parámetro mecánico</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Material de carcasa</td>
<td>PET-G</td>
</tr>
<tr class="even">
<td>Masa final del payload</td>
<td>1810 g</td>
</tr>
<tr class="odd">
<td>Restricción de masa</td>
<td>&lt;= 2 kg</td>
</tr>
<tr class="even">
<td>Volumen objetivo</td>
<td>100 x 100 x 150 mm</td>
</tr>
</tbody>
</table>

<img data-src="Figures/C4/captured_image_20250217_113221.jpg" style="width:74.0%" class="r-stretch"></section>
<section id="sistema-de-adquisición-y-control" class="slide level2">
<h2>Sistema de adquisición y control</h2>
<ul>
<li>Se implementó un flujo productor-consumidor para adquisición paralela de cámaras.</li>
<li>El pipeline integra captura, mosaico VIS/NIR, superposición de telemetría y guardado.</li>
<li>El sistema soporta captura de imagen fija y video durante operación en tierra o vuelo.</li>
<li>Rendimiento operativo reportado: hasta 24 FPS con registro de metadatos.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Comando</th>
<th>Función</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>s</code></td>
<td>Captura imagen (JPEG)</td>
</tr>
<tr class="even">
<td><code>v</code></td>
<td>Inicia/detiene grabación (AVI)</td>
</tr>
<tr class="odd">
<td><code>Enter</code></td>
<td>Cierre controlado del script</td>
</tr>
</tbody>
</table>
</section>
<section id="script-de-operación-configuración-gnss-y-sincronización-de-datos" class="slide level2">
<h2>Script de operación, configuración GNSS y sincronización de datos</h2>
<ul>
<li>Servicio de arranque para configuración determinística GNSS en cada boot.</li>
<li>Ajuste de enlace serie y perfiles NMEA para georreferenciación estable.</li>
<li>Servicio de sincronización automática a nube para respaldo de videos.</li>
<li>Diseño orientado a operación autónoma y tolerancia a fallos.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/gps_config.svg" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/sync.svg" style="width:100.0%"></p>
</div></div>
</section>
<section id="operación-remota-del-dispositivo-qbee" class="slide level2">
<h2>Operación remota del dispositivo QBee</h2>
<ul>
<li>Acceso remoto en red local mediante VNC.</li>
<li>Acceso remoto global mediante Raspberry Pi Connect.</li>
<li>Supervisión de captura y telemetría en tiempo real desde dispositivos externos.</li>
<li>Actualización continua de software vía repositorio privado y despliegue remoto.</li>
</ul>

<img data-src="Figures/C4/captured_image_20240201_174102.jpg" style="width:76.0%" class="r-stretch"></section></section>
<section>
<section id="pruebas-en-campo-capítulo-3" class="title-slide slide level1 center">
<h1>4. Pruebas en campo (Capítulo 3)</h1>

</section>
<section id="pruebas-en-tierra" class="slide level2">
<h2>Pruebas en tierra</h2>
<ul>
<li>Validación funcional en condiciones controladas antes de cada campaña aérea.</li>
<li>Verificación de inicio automático, captura de imagen, grabación de video y estabilidad.</li>
<li>Pruebas con fuente directa y batería interna del dispositivo.</li>
<li>Confirmación de operación simultánea de canales VIS/NIR y overlay GPS.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/captured_image_20240201_174102.jpg" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/captured_image_20250217_113221.jpg" style="width:100.0%"></p>
</div></div>
</section>
<section id="pruebas-en-condiciones-extremas-de-superficie" class="slide level2">
<h2>Pruebas en condiciones extremas de superficie</h2>
<ul>
<li>Se ejecutaron pruebas durante campaña antártica (dic 2024 - mar 2025).</li>
<li>Rango térmico de operación probado cercano a -6 C a 2 C.</li>
<li>Se observaron fallos intermitentes de arranque y de inicio de grabación.</li>
<li>Aun así, se obtuvieron capturas válidas que confirmaron viabilidad con mejoras térmicas.</li>
</ul>

<img data-src="Figures/C4/pinguinos.png" style="width:78.0%" class="r-stretch"></section>
<section id="pruebas-de-vuelo" class="slide level2">
<h2>Pruebas de vuelo</h2>
<ul>
<li>Vuelo 1: Cessna 208 Caravan (~5000 ft), operación estable y monitoreo remoto.</li>
<li>Vuelo 2: T-27 Tucano, operación autónoma bajo maniobras de hasta 4g.</li>
<li>No se reportaron caídas de adquisición durante los ensayos.</li>
<li>Se identificó sensibilidad de desempeño a condiciones de iluminación al atardecer.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/vuelo_caravan.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/t2.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="hallazgos-operativos-y-lecciones-aprendidas" class="slide level2">
<h2>Hallazgos operativos y lecciones aprendidas</h2>
<ul>
<li>El sistema demostró robustez mecánica y funcional en escenarios reales.</li>
<li>Factores críticos detectados: temperatura, saturación radiométrica y enfoque óptico.</li>
<li>El software multihilo fue estable por más de 30 horas continuas.</li>
<li>Se recomienda incorporar aislamiento térmico, control de saturación y watchdog de servicios.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Escenario</th>
<th>Resultado observado</th>
<th>Acción recomendada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tierra (diurno)</td>
<td>Operación estable</td>
<td>Mantener protocolo actual</td>
</tr>
<tr class="even">
<td>Frío extremo</td>
<td>Fallos intermitentes</td>
<td>Aislamiento y preheating</td>
</tr>
<tr class="odd">
<td>Vuelo con maniobras</td>
<td>Estable hasta 4g</td>
<td>Validar con más campañas</td>
</tr>
<tr class="even">
<td>Atardecer/baja luz</td>
<td>Degradación VIS</td>
<td>Ajuste dinámico de exposición</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="trabajo-de-laboratorio-y-caracterización-óptica-capítulo-4" class="title-slide slide level1 center">
<h1>5. Trabajo de laboratorio y caracterización óptica (Capítulo 4)</h1>

</section>
<section id="alcance-técnico-del-capítulo" class="slide level2">
<h2>Alcance técnico del capítulo</h2>
<ul>
<li>La validación experimental se divide en dos bloques: <strong>geométrico</strong> (FOV, AFOV, MTF, GRD) y <strong>espectral</strong> (respuesta relativa VIS/NIR).</li>
<li>El objetivo es cerrar la trazabilidad desde diseño teórico hasta desempeño medido bajo protocolo de laboratorio.</li>
<li>Se reportan ecuaciones, configuración de adquisición, control de incertidumbre y discrepancias frente a teoría.</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Bloque</th>
<th>Variable principal</th>
<th>Método aplicado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geométrico</td>
<td>FOV/AFOV</td>
<td>ISO 12233 + ajuste Deming</td>
</tr>
<tr class="even">
<td>Geométrico</td>
<td>MTF/GRD</td>
<td>Slanted-edge (ESF-&gt;LSF-&gt;FFT)</td>
</tr>
<tr class="odd">
<td>Espectral</td>
<td>Sensibilidad relativa</td>
<td>Barrido de filtros y combinaciones</td>
</tr>
</tbody>
</table>
</section>
<section id="modelo-geométrico-y-ajuste-experimental" class="slide level2">
<h2>Modelo geométrico y ajuste experimental</h2>
<p><span class="math display">\[
AFOV = 2 \tan^{-1}\left(\frac{H}{2f}\right),\quad
FOV(d)=2d\tan\left(\frac{AFOV}{2}\right)
\]</span></p>
<p><span class="math display">\[
FOV = \beta_1\cdot WD + \beta_0
\]</span></p>
<ul>
<li>El ajuste FOV-WD se hizo con <strong>regresión Deming</strong> para incorporar error en ambas variables.</li>
<li>Incertidumbre instrumental usada: orden de 1 mm en distancias de medición.</li>
<li>Se midieron componentes horizontales y verticales para VIS (Sistema 7) y NIR (Sistema 6).</li>
</ul>
</section>
<section id="datos-medidos-de-fov-base-experimental" class="slide level2">
<h2>Datos medidos de FOV (base experimental)</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>NIR WD_H [m]</th>
<th>NIR FOV_H [m]</th>
<th>NIR WD_V [m]</th>
<th>NIR FOV_V [m]</th>
<th>VIS WD_H [m]</th>
<th>VIS FOV_H [m]</th>
<th>VIS WD_V [m]</th>
<th>VIS FOV_V [m]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.071</td>
<td>0.035</td>
<td>0.087</td>
<td>0.035</td>
<td>0.092</td>
<td>0.035</td>
<td>0.107</td>
<td>0.035</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.331</td>
<td>0.231</td>
<td>0.350</td>
<td>0.180</td>
<td>0.379</td>
<td>0.239</td>
<td>0.303</td>
<td>0.138</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.650</td>
<td>0.468</td>
<td>0.650</td>
<td>0.349</td>
<td>0.694</td>
<td>0.458</td>
<td>0.700</td>
<td>0.342</td>
</tr>
</tbody>
</table>
</section>
<section id="ecuaciones-ajustadas-fov-wd-deming" class="slide level2">
<h2>Ecuaciones ajustadas FOV-WD (Deming)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Caso</th>
<th>Modelo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VIS-H</td>
<td><span class="math inline">\(FOV=(0.7025\pm0.0045)\,WD-(0.0288\pm0.0021)\)</span></td>
</tr>
<tr class="even">
<td>VIS-V</td>
<td><span class="math inline">\(FOV=(0.5171\pm0.0029)\,WD-(0.0197\pm0.0013)\)</span></td>
</tr>
<tr class="odd">
<td>NIR-H</td>
<td><span class="math inline">\(FOV=(0.7477\pm0.0031)\,WD-(0.0175\pm0.0013)\)</span></td>
</tr>
<tr class="even">
<td>NIR-V</td>
<td><span class="math inline">\(FOV=(0.5579\pm0.0034)\,WD-(0.0141\pm0.0015)\)</span></td>
</tr>
</tbody>
</table>

<img data-src="Figures/C4/FOV.png" style="width:88.0%" class="r-stretch"></section>
<section id="validación-en-altitudes-de-misión-predicción-vs-teoría" class="slide level2">
<h2>Validación en altitudes de misión (predicción vs teoría)</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Altitud</th>
<th>VIS Pred H [m]</th>
<th>VIS Theo H [m]</th>
<th>VIS Pred V [m]</th>
<th>VIS Theo V [m]</th>
<th>NIR Pred H [m]</th>
<th>NIR Theo H [m]</th>
<th>NIR Pred V [m]</th>
<th>NIR Theo V [m]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>50 m</td>
<td>35.10</td>
<td>33.54</td>
<td>25.84</td>
<td>25.16</td>
<td>37.37</td>
<td>35.64</td>
<td>27.88</td>
<td>26.73</td>
</tr>
<tr class="even">
<td>1000 m</td>
<td>702.50</td>
<td>670.87</td>
<td>517.08</td>
<td>503.15</td>
<td>747.70</td>
<td>712.80</td>
<td>557.90</td>
<td>534.60</td>
</tr>
<tr class="odd">
<td>5000 m</td>
<td>3512.00</td>
<td>3354.35</td>
<td>2585.48</td>
<td>2515.76</td>
<td>3737.00</td>
<td>3564.00</td>
<td>2788.89</td>
<td>2673.00</td>
</tr>
</tbody>
</table>
<ul>
<li>Error absoluto crece con altitud.</li>
<li>Error relativo se mantiene casi constante, sugiriendo sesgo geométrico sistemático (distorsión/paralaje residual).</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/absolute_error_plot_fov.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/relative_error_plot_fov.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="afov-experimental-vs-afov-teórico" class="slide level2">
<h2>AFOV experimental vs AFOV teórico</h2>
<p><span class="math display">\[
AFOV_{exp}=2\arctan\left(\frac{FOV}{2\,WD}\right),\quad
\Delta_{rel}=\frac{|AFOV_{exp}-AFOV_{teo}|}{AFOV_{teo}}\times 100\%
\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Caso (WD máximo)</th>
<th>AFOV exp [deg]</th>
<th>AFOV teórico [deg]</th>
<th>Error relativo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VIS-H</td>
<td>36.52</td>
<td>37.10</td>
<td>1.6 %</td>
</tr>
<tr class="even">
<td>VIS-V</td>
<td>27.46</td>
<td>28.24</td>
<td>2.8 %</td>
</tr>
<tr class="odd">
<td>NIR-H</td>
<td>39.60</td>
<td>39.30</td>
<td>0.8 %</td>
</tr>
<tr class="even">
<td>NIR-V</td>
<td>30.05</td>
<td>29.93</td>
<td>0.4 %</td>
</tr>
</tbody>
</table>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/afov_vis.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/afov_nir.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="magnificación-primaria-pmag" class="slide level2">
<h2>Magnificación primaria PMAG</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Altitud</th>
<th>PMAG VIS (Sys.7)</th>
<th>PMAG NIR (Sys.6)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>50 m</td>
<td><span class="math inline">\(1.62\times10^{-4}\)</span></td>
<td><span class="math inline">\(1.53\times10^{-4}\)</span></td>
</tr>
<tr class="even">
<td>1000 m</td>
<td><span class="math inline">\(8.12\times10^{-6}\)</span></td>
<td><span class="math inline">\(7.63\times10^{-6}\)</span></td>
</tr>
<tr class="odd">
<td>5000 m</td>
<td><span class="math inline">\(1.62\times10^{-6}\)</span></td>
<td><span class="math inline">\(1.53\times10^{-6}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li>Diferencia VIS-NIR &lt; 6 %, favorable para co-registro multiespectral.</li>
</ul>
</section>
<section id="fundamento-mtf-y-criterio-de-resolución" class="slide level2">
<h2>Fundamento MTF y criterio de resolución</h2>
<p><span class="math display">\[
g(x,y)=f(x,y)*h(x,y),\quad
LSF(x)=\frac{d}{dx}ESF(x),\quad
MTF(u)=\left|\mathcal{F}\{LSF(x)\}\right|
\]</span></p>
<p><span class="math display">\[
MTF(f_{im})=0.30
\]</span></p>
<ul>
<li>Se usa corte al 30 % como compromiso entre contraste útil y piso de ruido.</li>
<li>Este corte se convierte a resolución en terreno (GRD) usando PMAG.</li>
</ul>
</section>
<section id="control-de-calidad-mtf-limitación-y-mitigación-experimental" class="slide level2">
<h2>Control de calidad MTF: limitación y mitigación experimental</h2>
<ul>
<li>La carta ISO 12233 impresa en mate mostró histograma no ideal (picos espurios y dispersión).</li>
<li>Se adoptó patrón empírico de borde inclinado con ROI 104 x 104 px.</li>
<li>Se aplicó corrección de dark current y promedio de múltiples capturas para estabilizar ESF/LSF.</li>
</ul>
<div class="columns">
<div class="column" style="width:33%;">
<p><img data-src="Figures/C4/MTF_chart_hist.png" style="width:100.0%"></p>
</div><div class="column" style="width:33%;">
<p><img data-src="Figures/C4/hist_vis_MTF.png" style="width:100.0%"></p>
</div><div class="column" style="width:33%;">
<p><img data-src="Figures/C4/hist_nir_MTF.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="resultados-mtf-y-mtfa" class="slide level2">
<h2>Resultados MTF y MTFA</h2>
<p><span class="math display">\[
MTFA=\int_0^{f_c}MTF(f)\,df
\]</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/mtf_vis.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/mtf_nir.png" style="width:100.0%"></p>
</div></div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sistema/Canal</th>
<th><span class="math inline">\(f_c\)</span> [lp/mm]</th>
<th>MTFA [lp/mm]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VIS-R</td>
<td>57.72</td>
<td>34.45</td>
</tr>
<tr class="even">
<td>VIS-G</td>
<td>79.36</td>
<td>49.58</td>
</tr>
<tr class="odd">
<td>VIS-B</td>
<td>72.15</td>
<td>47.25</td>
</tr>
<tr class="even">
<td>VIS-Mono</td>
<td>72.15</td>
<td>45.05</td>
</tr>
<tr class="odd">
<td>NIR-Mono</td>
<td>79.36</td>
<td>46.48</td>
</tr>
</tbody>
</table>
</section>
<section id="frecuencia-de-corte-medida-vs-especificación" class="slide level2">
<h2>Frecuencia de corte medida vs especificación</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Sistema/Canal</th>
<th><span class="math inline">\(f_{im,meas}\)</span> [lp/mm]</th>
<th><span class="math inline">\(f_{im,theo}\)</span> [lp/mm]</th>
<th><span class="math inline">\(\Delta\)</span> [%]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VIS-R</td>
<td>57.72</td>
<td>85</td>
<td>-32.1</td>
</tr>
<tr class="even">
<td>VIS-G</td>
<td>79.36</td>
<td>85</td>
<td>-6.6</td>
</tr>
<tr class="odd">
<td>VIS-B</td>
<td>72.15</td>
<td>85</td>
<td>-15.1</td>
</tr>
<tr class="even">
<td>VIS-Mono</td>
<td>72.15</td>
<td>85</td>
<td>-15.1</td>
</tr>
<tr class="odd">
<td>NIR-Mono</td>
<td>79.36</td>
<td>120</td>
<td>-33.9</td>
</tr>
</tbody>
</table>
<ul>
<li>VIS: canal G con mejor transferencia (consistente con enfoque y aberración cromática longitudinal).</li>
<li>NIR: desviación grande frente a hoja de datos teórica, pero con desempeño real útil y estable.</li>
</ul>
</section>
<section id="grd-derivada-de-mtf" class="slide level2">
<h2>GRD derivada de MTF</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Sistema</th>
<th>Canal</th>
<th>GRD <span class="citation" data-cites="50">@50</span> m [cm]</th>
<th>GRD <span class="citation" data-cites="1000">@1000</span> m [cm]</th>
<th>GRD <span class="citation" data-cites="5000">@5000</span> m [cm]</th>
<th>GRD <span class="citation" data-cites="5000">@5000</span> m [m]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VIS</td>
<td>R</td>
<td>5.35</td>
<td>106.68</td>
<td>534.72</td>
<td>5.35</td>
</tr>
<tr class="even">
<td>VIS</td>
<td>G</td>
<td>3.89</td>
<td>77.59</td>
<td>388.91</td>
<td>3.89</td>
</tr>
<tr class="odd">
<td>VIS</td>
<td>B</td>
<td>4.28</td>
<td>85.34</td>
<td>427.78</td>
<td>4.28</td>
</tr>
<tr class="even">
<td>VIS</td>
<td>Mono</td>
<td>4.28</td>
<td>85.34</td>
<td>427.78</td>
<td>4.28</td>
</tr>
<tr class="odd">
<td>NIR</td>
<td>Mono</td>
<td>4.12</td>
<td>82.57</td>
<td>411.79</td>
<td>4.12</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Sistema/Canal</th>
<th>Altitud</th>
<th>GRD teórica [cm]</th>
<th>GRD experimental [cm]</th>
<th>Discrepancia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VIS-Mono</td>
<td>50 m</td>
<td>3.40</td>
<td>4.28</td>
<td>+25.9 %</td>
</tr>
<tr class="even">
<td>VIS-Mono</td>
<td>1000 m</td>
<td>69.20</td>
<td>85.34</td>
<td>+23.3 %</td>
</tr>
<tr class="odd">
<td>VIS-Mono</td>
<td>5000 m</td>
<td>346.00</td>
<td>427.78</td>
<td>+23.6 %</td>
</tr>
<tr class="even">
<td>NIR-Mono</td>
<td>50 m</td>
<td>1.90</td>
<td>4.12</td>
<td>+116.8 %</td>
</tr>
<tr class="odd">
<td>NIR-Mono</td>
<td>1000 m</td>
<td>39.10</td>
<td>82.57</td>
<td>+111.2 %</td>
</tr>
<tr class="even">
<td>NIR-Mono</td>
<td>5000 m</td>
<td>195.30</td>
<td>411.79</td>
<td>+110.8 %</td>
</tr>
</tbody>
</table>
</section>
<section id="lectura-crítica-de-resultados-geométricos" class="slide level2">
<h2>Lectura crítica de resultados geométricos</h2>
<ul>
<li>VIS presenta desviación estable ~23-26 % respecto a modelo ideal.</li>
<li>NIR presenta desviación &gt;100 % contra teórico de fabricante, pero GRD real cercana a VIS.</li>
<li>Conclusión técnica: el NIR no falla operativamente; el baseline teórico parece sobreestimado.</li>
</ul>
</section>
<section id="marco-radiométrico-para-bloque-espectral" class="slide level2">
<h2>Marco radiométrico para bloque espectral</h2>
<p><span class="math display">\[
Q_d(\theta,\lambda)=\frac{\pi}{4(F/\#)^2}\,O_e(\lambda)\,\Delta\lambda\,L(\lambda)\,\tau\,\cos^4\theta
\]</span></p>
<p><span class="math display">\[
C\propto \int S(\lambda)\,L(\lambda)\,d\lambda,\quad
R(\lambda_0)=\sum_{x,y}I_{filt}(x,y;\lambda_0)
\]</span></p>
<ul>
<li>La tesis entrega respuesta espectral <strong>relativa</strong> (sin calibración absoluta trazable).</li>
</ul>
</section>
<section id="procedimiento-espectral-de-laboratorio" class="slide level2">
<h2>Procedimiento espectral de laboratorio</h2>
<ul>
<li>Fuente: tungsteno ThorLabs OSL-2, validada con minispectrómetro Newport.</li>
<li>Colimación: lente plano-convexa 25 mm y maximización de potencia en detector.</li>
<li>Corrección de dark current del minispectrómetro: media 3513.97 counts.</li>
<li>Impacto de offset sin corregir: ~6.4 % del fondo de escala del equipo.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C3/tunsteno.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C3/filtros_respuestaspec.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="diseño-de-bandas-combinaciones-de-filtros" class="slide level2">
<h2>Diseño de bandas: combinaciones de filtros</h2>
<ul>
<li>Se evaluaron combinaciones de 1, 2 y 3 elementos: <strong>987 combinaciones</strong>.</li>
<li>Curvas objetivo gaussianas en 10 centros espectrales (VIS + NIR).</li>
<li>Métrica de selección: correlación de Pearson entre curva ideal y curva compuesta.</li>
<li>Se combinó criterio numérico con validación experimental de transmitancia útil.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C3/best_matches.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C3/filt_select.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="longitud-de-onda-central-y-fwhm-filtros-finales" class="slide level2">
<h2>Longitud de onda central y FWHM (filtros finales)</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Combinación</th>
<th><span class="math inline">\(\lambda_c\)</span> [nm]</th>
<th>FWHM [nm]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5 x Purple</td>
<td>427.07</td>
<td>42.55</td>
</tr>
<tr class="even">
<td>5 x Green</td>
<td>501.15</td>
<td>30.24</td>
</tr>
<tr class="odd">
<td>5 x 6 x Dark Green</td>
<td>509.78</td>
<td>17.57</td>
</tr>
<tr class="even">
<td>4 x Dark Blue</td>
<td>520.59</td>
<td>35.72</td>
</tr>
<tr class="odd">
<td>532 nm</td>
<td>532.16</td>
<td>4.59</td>
</tr>
<tr class="even">
<td>4 x Orange</td>
<td>574.43</td>
<td>26.73</td>
</tr>
<tr class="odd">
<td>2 x 3 x Yellow</td>
<td>605.39</td>
<td>20.21</td>
</tr>
<tr class="even">
<td>633 nm</td>
<td>632.19</td>
<td>5.05</td>
</tr>
<tr class="odd">
<td>1 x Purple x Red</td>
<td>701.89</td>
<td>77.16</td>
</tr>
<tr class="even">
<td>4 x Red</td>
<td>822.38</td>
<td>20.19</td>
</tr>
<tr class="odd">
<td>3 x 4 x Purple</td>
<td>826.43</td>
<td>18.98</td>
</tr>
<tr class="even">
<td>2 x 5</td>
<td>839.43</td>
<td>17.14</td>
</tr>
</tbody>
</table>
</section>
<section id="normalización-de-irradiancia-por-potencia-óptica" class="slide level2">
<h2>Normalización de irradiancia por potencia óptica</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Combinación</th>
<th>Potencia [mW]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5 x Purple</td>
<td>70.4</td>
</tr>
<tr class="even">
<td>1 x Purple x Red</td>
<td>68.1</td>
</tr>
<tr class="odd">
<td>5 x Green</td>
<td>53.3</td>
</tr>
<tr class="even">
<td>4 x Orange</td>
<td>43.1</td>
</tr>
<tr class="odd">
<td>2 x 3 x Yellow</td>
<td>36.8</td>
</tr>
<tr class="even">
<td>4 x Red</td>
<td>26.5</td>
</tr>
<tr class="odd">
<td>2 x 5</td>
<td>26.2</td>
</tr>
<tr class="even">
<td>4 x Dark Blue</td>
<td>23.7</td>
</tr>
<tr class="odd">
<td>5 x 6 x Dark Green</td>
<td>17.9</td>
</tr>
<tr class="even">
<td>3 x 4 x Purple</td>
<td>9.7</td>
</tr>
<tr class="odd">
<td>633 nm</td>
<td>1.47</td>
</tr>
<tr class="even">
<td>532 nm</td>
<td>0.42</td>
</tr>
</tbody>
</table>
<ul>
<li>Referencia de irradiancia en adquisición: <strong>0.42 mW</strong>.</li>
<li>El resto de combinaciones se atenuó para igualar ese nivel.</li>
</ul>
</section>
<section id="configuración-de-captura-para-respuesta-espectral" class="slide level2">
<h2>Configuración de captura para respuesta espectral</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parámetro común</th>
<th>VIS</th>
<th>NIR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gain</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Gamma</td>
<td>1.0</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td>Hue</td>
<td>0.0</td>
<td>–</td>
</tr>
<tr class="even">
<td>Height [px]</td>
<td>714</td>
<td>600</td>
</tr>
<tr class="odd">
<td>Width [px]</td>
<td>760</td>
<td>600</td>
</tr>
<tr class="even">
<td>OffsetX [px]</td>
<td>900</td>
<td>1026</td>
</tr>
<tr class="odd">
<td>OffsetY [px]</td>
<td>600</td>
<td>650</td>
</tr>
<tr class="even">
<td>BalanceRatio_Red</td>
<td>0.999</td>
<td>–</td>
</tr>
<tr class="odd">
<td>BalanceRatio_Blue</td>
<td>0.999</td>
<td>–</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sistema</th>
<th>Filtro</th>
<th>ExposureTime [ms]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VIS</td>
<td>1 x Purple x Red</td>
<td>2859.217</td>
</tr>
<tr class="even">
<td>VIS</td>
<td>2 x 3 x Yellow</td>
<td>2916.174</td>
</tr>
<tr class="odd">
<td>VIS</td>
<td>3 x 4 x Purple</td>
<td>11.391</td>
</tr>
<tr class="even">
<td>VIS</td>
<td>4 x Dark Blue</td>
<td>3998.348</td>
</tr>
<tr class="odd">
<td>VIS</td>
<td>4 x Orange</td>
<td>888.522</td>
</tr>
<tr class="even">
<td>VIS</td>
<td>5 x 6 x Dark Green</td>
<td>5661.478</td>
</tr>
<tr class="odd">
<td>VIS</td>
<td>5 x Purple</td>
<td>47000.520</td>
</tr>
<tr class="even">
<td>VIS</td>
<td>5 x Green</td>
<td>2870.609</td>
</tr>
<tr class="odd">
<td>NIR</td>
<td>4 x Red</td>
<td>29.372</td>
</tr>
<tr class="even">
<td>NIR</td>
<td>3 x 4 x Purple</td>
<td>36.715</td>
</tr>
<tr class="odd">
<td>NIR</td>
<td>2 x 5</td>
<td>29.372</td>
</tr>
</tbody>
</table>
</section>
<section id="dark-current-repetibilidad-y-clipping" class="slide level2">
<h2>Dark current, repetibilidad y clipping</h2>
<ul>
<li>Por configuración: 50 frames iluminados + 50 dark frames.</li>
<li>Corrección por sustracción de dark master y promedio para reducir ruido aleatorio.</li>
<li>En NIR, estadísticos dark permanecen bajos (media/varianza ~1e-3, máximo 1 count).</li>
<li>Se verificó ausencia de saturación con análisis de cuantiles (<span class="math inline">\(q_{99.9}&lt;255\)</span> en 8 bits).</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/dc_examplevis.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/dc_examplenir.png" style="width:100.0%"></p>
</div></div>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/vis_quartiles_final.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/nir_quantiles.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="respuesta-espectral-relativa-final" class="slide level2">
<h2>Respuesta espectral relativa final</h2>
<ul>
<li>VIS presenta la estructura esperada de tres lóbulos (B-G-R) coherente con sensor Bayer.</li>
<li>NIR presenta respuesta unimodal dentro de 820-840 nm.</li>
<li>En NIR, la dispersión entre puntos fue baja (CV ~5.5 %) bajo irradiancia controlada.</li>
<li>Limitación metodológica: respuesta integrada por banda (no estimación absoluta puntual).</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="Figures/C4/vis_spec_res.png" style="width:100.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="Figures/C4/nir_spec_res.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="cierre-de-requisitos-del-capítulo" class="slide level2">
<h2>Cierre de requisitos del capítulo</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Requisito</th>
<th>Meta</th>
<th>Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Masa payload</td>
<td>&lt;= 2 kg</td>
<td>1.81 kg</td>
</tr>
<tr class="even">
<td>Costo materiales</td>
<td>&lt;= 1500 USD</td>
<td>1318 USD</td>
</tr>
<tr class="odd">
<td>MTF mínima</td>
<td>&gt;= 40 lp/mm</td>
<td>VIS/NIR &gt; 70 lp/mm</td>
</tr>
<tr class="even">
<td>Resolución <span class="citation" data-cites="50">@50</span> m</td>
<td>&lt;= 7.35 cm</td>
<td>VIS 4.28 cm / NIR 4.12 cm</td>
</tr>
<tr class="odd">
<td>Curvas espectrales VIS/NIR</td>
<td>Consistentes</td>
<td>Cumplido (relativo)</td>
</tr>
<tr class="even">
<td>Radiometría absoluta</td>
<td>Trazable</td>
<td>Pendiente</td>
</tr>
</tbody>
</table>
<ul>
<li>Resultado central del Cap. 4: desempeño geométrico y espectral relativo validado.</li>
<li>Brecha para cierre completo de tesis: calibración radiométrica absoluta con trazabilidad metrológica.</li>
</ul>
</section></section>
<section>
<section id="conclusiones-y-cierre-capítulo-5" class="title-slide slide level1 center">
<h1>6. Conclusiones y cierre (Capítulo 5)</h1>

</section>
<section id="contribución-integral-de-la-tesis" class="slide level2">
<h2>Contribución integral de la tesis</h2>
<ul>
<li>Se consolidó una ruta completa de ingeniería: <strong>requisitos -&gt; diseño -&gt; procura/integración -&gt; validación en campo -&gt; caracterización óptica/radiométrica</strong>.</li>
<li>El sistema HuMath QBee responde al problema central con una carga multiespectral <strong>VIS/NIR ligera, robusta y desplegable</strong> en plataforma aérea C3.</li>
<li>El trabajo deja evidencia cuantitativa para disminuir incertidumbre técnica en iteraciones futuras del proyecto.</li>
</ul>
</section>
<section id="conclusión-del-capítulo-2-diseño-óptico-trazable-y-replicable" class="slide level2">
<h2>Conclusión del Capítulo 2: diseño óptico trazable y replicable</h2>
<ul>
<li>Se compararon <strong>8 configuraciones VIS/NIR</strong> bajo compromisos de MTF, FOV, masa y costo.</li>
<li>La selección final (ópticas <strong>8.5 mm VIS</strong> y <strong>8 mm NIR</strong> con sensores Alvium 1800) cumple metas para <strong>50 m a 5 km</strong>.</li>
<li>El análisis paramétrico mostró (_{}) desde ~<strong>1.9 cm</strong> (baja altura) hasta ~<strong>3.5 m</strong> (mapeo de gran cobertura).</li>
<li>La trazabilidad evitó sobre-diseño y dejó una plantilla reutilizable para futuros cambios de misión/sensor.</li>
</ul>
</section>
<section id="conclusión-del-capítulo-3-factibilidad-de-integración-y-robustez-operacional" class="slide level2">
<h2>Conclusión del Capítulo 3: factibilidad de integración y robustez operacional</h2>
<ul>
<li>La procura y construcción confirmaron viabilidad técnica de la solución seleccionada.</li>
<li>Se integraron sensores Alvium U-500c (VIS) y U-501m (NIR), carcasas PET-G, filtros y montaje modular.</li>
<li>Se alcanzó una masa de <strong>1810 g</strong> (incluyendo cableado y herrajes), dentro de la restricción del proyecto.</li>
<li>Las pruebas (banco prolongado, maniobras de hasta <strong>4g</strong>, y operación cercana a <strong>0 C</strong>) validaron robustez mecánica y de adquisición.</li>
<li>Se identificaron mejoras necesarias: aislamiento térmico, atenuación ND y watchdog de buffers.</li>
</ul>
</section>
<section id="conclusión-del-capítulo-4-caracterización-óptica-y-radiométrica-relativa" class="slide level2">
<h2>Conclusión del Capítulo 4: caracterización óptica y radiométrica relativa</h2>
<ul>
<li>El canal VIS conservó la firma esperada de <strong>tres lóbulos RGB</strong>; el canal NIR mostró banda suave centrada en <strong>820-840 nm</strong>.</li>
<li>El protocolo (irradiancia controlada + sustracción de dark frame + repetibilidad estadística) separó ruido de atenuación por filtros.</li>
<li>Se obtuvieron curvas de responsividad relativa útiles para normalización de campañas de campo.</li>
<li>Brecha técnica para cierre metrológico: calibración absoluta con referencia <strong>AM1.5G</strong>, linealidad vs irradiancia y presupuesto formal de ruido.</li>
</ul>
</section>
<section id="estado-de-madurez-y-cierre-de-objetivos" class="slide level2">
<h2>Estado de madurez y cierre de objetivos</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Objetivo de tesis</th>
<th>Estado</th>
<th>Evidencia principal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Diseño y selección óptica</td>
<td>Cumplido</td>
<td>Evaluación de 8 sistemas y selección final VIS/NIR</td>
</tr>
<tr class="even">
<td>Integración de hardware</td>
<td>Cumplido</td>
<td>Payload 1.81 kg funcional en plataforma C3</td>
</tr>
<tr class="odd">
<td>Validación operacional</td>
<td>Cumplido (preliminar avanzado)</td>
<td>Ensayos en tierra y vuelo con exigencia dinámica</td>
</tr>
<tr class="even">
<td>Caracterización espectral</td>
<td>Cumplido (relativo)</td>
<td>Curvas VIS/NIR consistentes y repetibles</td>
</tr>
<tr class="odd">
<td>Trazabilidad radiométrica absoluta</td>
<td>Pendiente</td>
<td>Requiere calibración con fuentes y patrones trazables</td>
</tr>
</tbody>
</table>
</section>
<section id="trabajo-futuro-capítulo-5-hoja-de-ruta-en-3-fases" class="slide level2">
<h2>Trabajo futuro (Capítulo 5): hoja de ruta en 3 fases</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Fase</th>
<th>Enfoque</th>
<th>Entregables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 (corto plazo)</td>
<td>Calibración radiométrica absoluta</td>
<td>Ganancias, linealidad, SNR y ruido vs irradiancia con referencia ASTM G-173 (AM1.5D/AM1.5G)</td>
</tr>
<tr class="even">
<td>2 (mediano plazo)</td>
<td>Validación operacional extendida</td>
<td>Vuelos georreferenciados, análisis de vibración, sincronía VIS/NIR, ortomosaicos y cubos multiespectrales</td>
</tr>
<tr class="odd">
<td>3 (largo plazo)</td>
<td>Escalamiento de pipeline y arquitectura</td>
<td>Flujo reproducible (calibración + corrección atmosférica + productos biofísicos), integración IMU/GNSS y expansión a nuevos filtros/SWIR</td>
</tr>
</tbody>
</table>
<ul>
<li>Proyección estratégica: evolución hacia una variante <strong>HuMath Space Bee</strong> para escenarios orbitales.</li>
</ul>
</section>
<section id="cierre" class="slide level2">
<h2>Cierre</h2>
<ul>
<li>La tesis entrega un sistema funcional y un marco de decisión técnico para su evolución.</li>
<li>El aporte principal no es solo el prototipo, sino una metodología replicable para instrumentación multiespectral nacional.</li>
<li>El siguiente salto de valor científico está en cerrar calibración absoluta y campañas operacionales de mayor escala.</li>
</ul>

<img data-src="Figures/C4/vuelo_caravan.png" style="width:78.0%" class="r-stretch"></section></section>
<section id="agradecimientos" class="title-slide slide level1 center">
<h1>7. Agradecimientos</h1>
<ul>
<li>A mi familia, por su apoyo y cariño incondicional durante todos estos años.</li>
<li>A mis amigos, por su compañía y escucha en los momentos difíciles, y por los grandes instantes de diversión, música y aventura.</li>
<li>A mi amiga, socia, compañera y directora académica <strong>Olga Lucia Quintero Montoya</strong>, por su confianza, apoyo en este proyecto y valiosas lecciones de vida.</li>
<li>A la <strong>Fuerza Aérea Colombiana</strong>, por su disposición para probar las Abejas en sus aeronaves, especialmente al comandante del <strong>Comando Aéreo de Combate No.&nbsp;2 y 5, Alejandro Vélez Ospina</strong>.</li>
<li>A mis compañeros de trabajo y amigos <strong>Sara, Neyder, Fernando y Pablo</strong>, por su soporte diario.</li>
<li>A <strong>Valeria Solórzano Araque</strong> y <strong>Lisseth Milena Cruz Ruiz</strong>, líderes del equipo de manufactura del proyecto C3, por su liderazgo en el diseño CAD de la QBee, sus enseñanzas y su excelente labor.</li>
<li>A la <strong>Dra. Elena Montilla Rosero</strong>, por su ejemplo como investigadora y docente.</li>
<li>A <strong>Cristian Lopera Trujillo</strong>, por su aporte clave en el laboratorio de óptica.</li>
<li>Al <strong>Dr.&nbsp;Andrés Yarce Botero</strong> y al <strong>Dr.&nbsp;Alejandro Madrid Sánchez</strong>, por su guía durante el proceso de diseño de las Abejas.</li>
<li>A mis docentes de la universidad, por su disposición y paciencia para enseñarme la metodología del laboratorio de óptica.</li>
<li>A la <strong>Universidad EAFIT</strong> y a <strong>Ricardo Mejía Gutiérrez</strong> (Dir. de Investigación), por brindarme la oportunidad de formarme como magíster en Física Aplicada.</li>
</ul>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="slides-outline_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="slides-outline_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="slides-outline_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="slides-outline_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="slides-outline_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="slides-outline_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="slides-outline_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="slides-outline_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="slides-outline_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="slides-outline_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>